# Generated by Django 4.2.6 on 2023-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_carouselcat_carousel_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='pubblicato',
            field=models.BooleanField(default=False, verbose_name='Pubblicato'),
        ),
    ]
