# Generated by Django 4.2.6 on 2023-11-10 16:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_carousel_pubblicato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='corpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Testo/Contenuto della slide'),
        ),
    ]
