# Generated by Django 4.2.6 on 2023-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cap',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comune',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comune di residenza'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Indirizzo di spedizione'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
