# Generated by Django 4.2.6 on 2023-11-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_cap_userprofile_comune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CAP'),
        ),
    ]
