# Generated by Django 4.2.6 on 2023-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_cf_alter_userprofile_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Latina', 'LT'), ('Roma', 'RM'), ('Milano', 'Mi')], default=None, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
