# Generated by Django 4.2.6 on 2023-11-16 14:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cat_princ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='shop.categorie')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('img', models.ImageField(default='prodotti/noimg.png', upload_to='prodotti/%Y/%m/%d')),
                ('descrizione', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Testo/Contenuto della slide')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita', models.IntegerField(default=0, verbose_name='Quantità in magazzino')),
                ('pubblicato', models.BooleanField(default=False)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='shop.categorie')),
            ],
            options={
                'verbose_name': 'prodotti',
                'verbose_name_plural': 'prodotti',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_prodot_id_ccea80_idx'), models.Index(fields=['nome'], name='shop_prodot_nome_243167_idx'), models.Index(fields=['data_inserimento'], name='shop_prodot_data_in_51e648_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['nome'], name='shop_catego_nome_4aa0cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('slug', 'cat_princ')},
        ),
    ]
